name: despliegeCosmonaut

on:
  push:
    branches:
    - samv
    - RJR

jobs:
  firebase-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: '14.x'
    - run: npm install
    - run: npm install -g @angular/cli
    - run: ng build --prod
    - uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.TOKEN_FIREBASE }}
  despliege-googlestorage:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: '14.x'
    - run: npm install
    - run: npm install -g @angular/cli
    - run: ng build --prod --base-href /cosmonaut-public-front/
    - uses: mathieu-bour/setup-gcloud@1.3.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.ARCHIVO_GOOGLECLOUD }}
          export_default_credentials: true
    - run: cd dist/cosmonaut-front/ && gsutil cp -r *  gs://cosmonaut-public-front/

